### ISSUE TITLE
Mainloop and enqueue logic

### ISSUE THREAD

**Issue by giancarlobi** [esmero/strawberry_runners#12]
**MainLoop logic** 
(see https://github.com/esmero/strawberry_runners/blob/5c0d6889cc09df02634ec429a68fdab8788e196b/src/Scripts/mainLoop.php#L41):

- Loop is executed every $queuecheckPeriod (i.e. 3 s)
- At each execution loop updates 'strawberryfield_mainLoop_keepalive' = \Drupal::time()->getCurrentTime()
- If queue empty for $idleCycle_timeout (i.e. 5) consecutive cycles then loop stop
- If queue not empty then reset counter $cycleBefore_timeout to $idleCycle_timeout

**Enqueue logic** 
(see https://github.com/esmero/strawberry_runners/blob/5c0d6889cc09df02634ec429a68fdab8788e196b/test/submit.php#L32):

1. push item to process on the queue then check mainloop is running or to start

2. does mainloop need wakeup?

- $submitTime = \Drupal::time()->getCurrentTime(); (time when item was enqueued)
- set $NxqueuecheckPeriod = 2 * $queuecheckPeriod (safe wait time)

- wait (A) mainloop executed one time after submit ($submitTime - $lastRunTime < 0)
**OR**
wait (B) for $NxqueuecheckPeriod after submit time

- If (B) then Mainloop has to be started else if (A) Mainloop already running nothing to do

**Comment by DiegoPino** [comment]
@giancarlobi hi.

I'm starting to code this since I feel its the most important part to get a seamless experience for end users.
But now I have a few questions/ideas:

Options:
1.- What if the script simply runs as a daemon and some external service makes sure it is never dead/restarts if it dies? Here is an idea: https://github.com/beldpro-ci/s6-entrypoint/blob/master/Dockerfile (can be also not dockerized for you)
2.- We do as you say. We actually wake it up if not running. Questions is when? As explained here, when a new thing is enqueued? What if something fails/http issues, disk full, etc ? Who starts it again? 
3.- We do a mixed approach. We use https://re-cycledair.com/php-dark-arts-multi-processing-part-2 pcntl to create a child process and detach it. The child process is actually our main loop. We store the PID. We actually use Unix PID check to see if the process is running? Issue with this approach is i may not dockerize it and make it a standalone process..? Benefit is I can even assign priority and the amount of ram/cpu it will use

but there is a more pressing question: Multisites. If I have (and I have) a single Drupal managing multiple domains. Each domain/drush will need its own Script OR/ a single script that is aware of all domains.

**Comment by giancarlobi** [comment]
@DiegoPino After a first read to your options and multisite, I have these thoughts:
- If I understood well, (1) and (3) need a piece more (as a docker) that seems to me a complexity more to manage queue
- I don't know well how drupal cron works, is it common to all sites in a multisite installation?
- About (2), to simplify why not wake-up main loop by cron? If multisite, cron could be able to check each queues and eventually start main loop? in multisite, is a single main loop sufficient?
- I feel that option (2) is more simple regarding other ones, but take this as a "sensation" and without some know-how about cron and other things you know better then me
Also, we thinking in runners as a module to manage ingesting so it and main loop can be installed on a "ingesting" machine and the front-end can be on a second exposed vm, right?

**Comment by DiegoPino** [comment]
@giancarlobi thanks.

1.-  1 and 3 yes. This could be an enterprise option, for larger installs. 
2.- Each site has its own cron invocation. What Cron item would need to do, if we go that route is pass the "site folder" to the mainloop. If we do that, then in each multisite will have its own maintop process (since between sites they can also not access state/etc). Other option is that the mainloop can read from a config file all multisite and do that? On loop inside the same script per site.  This is better than just Cron because it makes all non blocking and we can control how often we run the queues without having the queues itself being managed by cron.
Option 2 is the simplest. Only issue would be that cron may run not very often? Still, we can start the Loop via CRON and also when a post processor (at least check) is invoked. So we may have two good options.

I will start with the simples case here. And will follow up with you. Thanks again.

Related to our previous discussion. No Queue really has any priority, if we run on a loop, which one runs first is basically as good as the other. One will feed the next one and back. It really makes more sense to run the heavier one first. That way if there are relegated Objects we go for them first, and then add more from the other one.

lastly: Easier to run via main loop the drush queue:run? or to run the queue getting item by item? Last one has the benefit that I can tell the looper to only process e.g max 10 per queue and then go for the next queue.

Both AMI and SBR use queues so I may as well write code for both OR, make it into SBF?


Ingesting machine. yes. If we go 1 or 2, we may want to have supervising process to allow that. But for now, this seems like a good option

**Comment by giancarlobi** [comment]
On 30/12/20 21:25, Diego Pino Navarro wrote:
>
> @giancarlobi <https://github.com/giancarlobi> thanks.
>
> 1.- 1 and 3 yes. This could be an enterprise option, for larger installs.
>
Ok, I agree,  specialized server to manage big ingesting/transformation
>
> 2.- Each site has its own cron invocation. What Cron item would need 
> to do, if we go that route is pass the "site folder" to the mainloop. 
> If we do that, then in each multisite will have its own maintop 
> process (since between sites they can also not access state/etc). 
> Other option is that the mainloop can read from a config file all 
> multisite and do that?
>
That is, for a multisite only one mainloop, is it right? and mainloop 
has to be able to "extract" queue elements from each site and execute them?
>
> On loop inside the same script per site. This is better than just Cron 
> because it makes all non blocking and we can control how often we run 
> the queues without having the queues itself being managed by cron.
>
I agree, not triggered by cron give us some more control on queue execution
>
> Option 2 is the simplest. Only issue would be that cron may run not 
> very often? Still, we can start the Loop via CRON and also when a post 
> processor (at least check) is invoked. So we may have two good options.
>
Yes, we can think in cron as a "backup" method to start mainloop if 
something goes wrong starting loop when elements are enqueued.
>
> I will start with the simples case here. And will follow up with you. 
> Thanks again.
>
Thanks to you and happy if I can help in any manner
>
> Related to our previous discussion. No Queue really has any priority, 
> if we run on a loop, which one runs first is basically as good as the 
> other. One will feed the next one and back. It really makes more sense 
> to run the heavier one first. That way if there are relegated Objects 
> we go for them first, and then add more from the other one.
>
ok
>
> lastly: Easier to run via main loop the drush queue:run? or to run the 
> queue getting item by item? Last one has the benefit that I can tell 
> the looper to only process e.g max 10 per queue and then go for the 
> next queue.
>
I'm for item by item too. Running the whole queue can be blocking and 
without any control as you highlight, better item by item so between 
items we can make some decisions or check other status and decide to 
temporary pause queue processing or other commands. This queue is 
"background" type so user knows that elements would be processed in a 
best effort manner, that is we can decide to process queue in the night 
because the server has more resource available.
>
> Both AMI and SBR use queues so I may as well write code for both OR, 
> make it into SBF?
>
Mainly it depends on you how think better regarding code logic. Anyway, 
I think that SBF is the core and queue manage/control has to be into the 
core but it's just a philosophical opinion.
>
> Ingesting machine. yes. If we go 1 or 2, we may want to have 
> supervising process to allow that. But for now, this seems like a good 
> option
>
Yes, we have time to think about that later, friend.

Take care

**Comment by DiegoPino** [comment]
Implemented in strawberry field, thanks for the good conversation!
