### ISSUE TITLE
Ingested in-place files on S3 are queued for composting

### ISSUE THREAD

**Issue by patdunlavey** [esmero/strawberry_runners#83]
We noticed that we're seeing messages in our logs like this: 
```
"Attempt to compost an unsafe File with path s3://media/cna_001693/cna_001693_metadata.xml was made. Please manually delete it or lower/configure your security settings and code overrides defining what a Safe Path is."
```
Fortunately, `CompostQueueWorker::processItem()` is pretty paranoid about what is safe to delete (thank you Diego!!).

I'm trying to remember how file persistence works in this case where the file has been uploaded to its final destination in S3, and we just provide the path to it in our AMI spreadsheet. Is it just when the source path for the file in the AMI csv is inside the "Relative Path for Persisting Files" that it does not copy the file over and simply saves the path to the file? 

My hunch is that `AbstractPostProcessorQueueWorker::processItem()` [where it sets $needs_localfile_cleanup](https://github.com/esmero/strawberry_runners/blob/0.5.0/src/Plugin/QueueWorker/AbstractPostProcessorQueueWorker.php#L258) needs to be aware of whether the file is temporary or not. One way to do that might be to compare the original file location with the saved file location. But I haven't taken the time to figure out where we would find that inside this method.

I'd be very happy to take a whack at a solution for this @DiegoPino if you like and can give me a bit of direction as to the best way to handle this.

**Comment by patdunlavey** [comment]
Derek helpfully found that this in-place behavior was, at least in part, my doing! https://github.com/esmero/strawberryfield/pull/198

**Comment by DiegoPino** [comment]
@patdunlavey from my perspective, the logging is correct and expected, I don't see this is an issue that should be solved at this level, mostly because you can always override via a hook the final destination of the files (as you do) and at the abstract processor side of things, the file is not yet permanent, not clear (bc of the hook you can apply at the strawberryfield level) if that location is going to be the final one. 

What I do see is that message might be molesting you. So there are two choices here:

- Change the order of operation in the composter. If you see https://github.com/esmero/strawberryfield/blob/ce448a0ebe16650df19708459a4600d2c4d2c9e1/src/Plugin/QueueWorker/CompostQueueWorker.php#L262 I'm already checking if the File is attached to an entity, I just do it afterwards bc it is a more expensive operation that limiting the deletion of files in safe locations (e.g s3://) 
- Give you a setting to not log these.

The gist for me is: AMI and SBF are independent modules and safety (and me being paranoid about what to delete) is important, but at the end, given the many hooks to override we produce plus the fact that file persistence happens not in AMI but in strawberryfield and some operations might end being async, I prefer for the composter nor AMI to make assumptions of each other, but I can totally remove the log (it is a harmless log) if that is needed, or check first if the file is already attached (more code/more test though) if that is needed. 

Let me know what you both think or if I am not getting the issue here (I might be not getting it!)

**Comment by patdunlavey** [comment]
Thanks Diego! I think you understand my issue perfectly, and I appreciate your helping me to understand the bigger picture, and some of the good reasons (e.g. async) for why things are the way things are. 

As I understand what you're saying, there is no practical way to know inside the AbstractPostProcessorQueueWorker::processItem() function whether it is safe to delete the file. So the compost queueing is going to happen, and the logic for whether or not to actually perform the deletion needs to occur inside CompostQueueWorker::processItem(). Is that right?

Then the question is how noisy to be about logging this. I do think the logging is important - I wouldn't want to remove it wholesale, and I'm not sure that a setting to turn off the logging would be desirable, at least for us. On the other hand, changing the order of operation (check file attachment first, before logging and re-enqueueing) seems expensive to me too - though not having to re-enqueue things that we know will eventually "fail" could maybe get some of that performance back? I wonder if it might make any sense to make this configurable. I.e. don't change the order for everybody. For some users, the performance penalty might be worth it?

**Comment by DiegoPino** [comment]
Thanks Pat, yes that is right CompostQueueWorker::processItem() is where the logic needs to live.
Performance wise, checking for this here:
```PHP
   $files = $this->entityTypeManager
      ->getStorage('file')
      ->loadByProperties(['uri' => $data->uri]);
```
Might be expensive bc `uri` is not a unique Key Drupal's schema. Our production repositories might have between 200K-500K files. But also not terrible expensive. There is no way we can check if a File is temporary without loading the File Entity itself.

Let me sleep on this one. So far these are my ideas:

- I believe we can add a config/checkbox to not log unsafe files.
- We can also make two separate checks for "safety". Unsafe, and  Critical (e.g .php files .env etc pretty unsafe, s3:// well, might or not be safe depending on other stuff) and lower the verbosity based on where the file is found to be unsafe
- We don't need to re-enqueue unsafe files, those could be simply removed from the queue/future by returning empty. Chances are if unsafe today, unsafe tomorrow.

Is your log cluttering?

**Comment by DiegoPino** [comment]
This is solved in https://github.com/esmero/strawberryfield/issues/287. So closing. Thanks @patdunlavey
